// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ExPerFTzudoNOAahR4xwdkJZyyLIWMY',
    appId: '1:914112229640:web:98af0b73c0353c5b093cbd',
    messagingSenderId: '914112229640',
    projectId: 'bamananlearn',
    authDomain: 'bamananlearn.firebaseapp.com',
    storageBucket: 'bamananlearn.appspot.com',
    measurementId: 'G-NQR963M9VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzjgKKuUo8ABM3hhtwKKjO2RRjG_t6qY',
    appId: '1:914112229640:android:ffa9a46cad095335093cbd',
    messagingSenderId: '914112229640',
    projectId: 'bamananlearn',
    storageBucket: 'bamananlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgYX7GG88-XLQR4YIGgeoowxyBSvItsWo',
    appId: '1:914112229640:ios:c8e9b5cd5ddc9c55093cbd',
    messagingSenderId: '914112229640',
    projectId: 'bamananlearn',
    storageBucket: 'bamananlearn.appspot.com',
    iosBundleId: 'com.example.bambaraLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgYX7GG88-XLQR4YIGgeoowxyBSvItsWo',
    appId: '1:914112229640:ios:c9a7e4fbe6b98270093cbd',
    messagingSenderId: '914112229640',
    projectId: 'bamananlearn',
    storageBucket: 'bamananlearn.appspot.com',
    iosBundleId: 'com.example.bambaraLearn.RunnerTests',
  );
}
